// lib/dashboard.js
//
// Phase 10: read-only aggregation for the final dashboard. Every number here
// is derived directly from existing Phase 3-8 tables — no new learning logic,
// no AI calls, nothing fabricated. Recommendations are read from the
// Recommendation table as last generated by Phase 8 (lib/recommendations.js)
// rather than re-running that engine on every dashboard load, so opening the
// dashboard never triggers a fresh Groq call.

import prisma from "@/lib/prisma";
import { normalizeConceptName } from "@/lib/conceptNormalization";
import { ACCEPTED_VERDICT } from "@/lib/constants";
import { priorityLabelFor } from "@/lib/recommendations";

const DAY_MS = 24 * 60 * 60 * 1000;
const MIN_TREND_ATTEMPTS = 3;
const RECENT_ACTIVITY_LIMIT = 8;

function daysBetween(a, b) {
  return (a.getTime() - b.getTime()) / DAY_MS;
}

function describeDueLabel(nextReviewAt, now) {
  const diffDays = Math.round(daysBetween(nextReviewAt, now));
  if (diffDays <= 0) {
    const overdueDays = Math.abs(diffDays);
    return overdueDays === 0 ? "Due today" : `Overdue by ${overdueDays} day${overdueDays === 1 ? "" : "s"}`;
  }
  if (diffDays === 1) return "Due tomorrow";
  return `Due in ${diffDays} days`;
}

/**
 * Picks the concept with the most Micro-Proof attempts (>= MIN_TREND_ATTEMPTS)
 * and returns its real score history in attempt order. This is genuine
 * stored history (Phase 5 MicroProofAttempt rows) — never fabricated points.
 * Returns null if no concept has enough attempts yet.
 */
function buildMasteryTrend(attempts) {
  const byConcept = new Map();
  for (const a of attempts) {
    const name = normalizeConceptName(a.microProof?.concept?.name);
    if (!name) continue;
    if (!byConcept.has(name)) byConcept.set(name, []);
    byConcept.get(name).push(a);
  }

  let best = null;
  for (const [concept, list] of byConcept) {
    if (list.length < MIN_TREND_ATTEMPTS) continue;
    if (!best || list.length > best.list.length) best = { concept, list };
  }
  if (!best) return null;

  return {
    concept: best.concept,
    data: best.list.map((a, i) => ({
      attempt: i + 1,
      score: a.score,
      date: a.createdAt,
    })),
  };
}

function computeFailurePatterns(failureAnalyses) {
  const counts = new Map();
  for (const f of failureAnalyses) {
    const concept = normalizeConceptName(f.concept) || f.concept;
    counts.set(concept, (counts.get(concept) || 0) + 1);
  }
  return Array.from(counts.entries())
    .map(([concept, count]) => ({ concept, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 3);
}

function buildRecentActivity({ acceptedSubmissions, failureAnalyses, microProofAttempts, masteries }) {
  const events = [];

  for (const s of acceptedSubmissions) {
    events.push({
      type: "SOLVED",
      label: `Solved "${s.problem.title}"`,
      detail: s.problem.difficulty,
      date: s.timestamp,
    });
  }

  for (const f of failureAnalyses) {
    events.push({
      type: "FAILURE",
      label: `Failure analyzed: ${f.concept}`,
      detail: f.failureCategory,
      date: f.createdAt,
    });
  }

  for (const a of microProofAttempts) {
    const conceptName = a.microProof?.concept?.name || "a concept";
    const isRevision = a.intervalDaysAfterReview !== null && a.intervalDaysAfterReview !== undefined;
    events.push({
      type: isRevision ? "REVISION" : "MICROPROOF",
      label: isRevision ? `Revision reviewed: ${conceptName}` : `Micro-Proof completed: ${conceptName}`,
      detail: `Score ${a.score}/10`,
      date: a.createdAt,
    });
  }

  for (const m of masteries) {
    if (m.updatedAt.getTime() === m.createdAt.getTime()) continue; // never re-evaluated since creation
    events.push({
      type: "MASTERY",
      label: `Mastery updated: ${m.concept}`,
      detail: `${m.masteryScore}%`,
      date: m.updatedAt,
    });
  }

  return events.sort((a, b) => b.date - a.date).slice(0, RECENT_ACTIVITY_LIMIT);
}

/**
 * Fetches and aggregates everything the dashboard needs in one pass.
 * Every query is scoped to `clerkUserId`. Server-only.
 *
 * @param {string} clerkUserId
 * @returns {Promise<object>}
 */
export async function getDashboardData(clerkUserId) {
  const now = new Date();

  const [masteries, revisionSchedules, recommendations, failureAnalyses, microProofAttempts, acceptedSubmissions] =
    await Promise.all([
      prisma.conceptMastery.findMany({ where: { clerkUserId } }),
      prisma.revisionSchedule.findMany({
        where: { clerkUserId },
        include: { mastery: { select: { status: true } } },
        orderBy: { nextReviewAt: "asc" },
      }),
      prisma.recommendation.findMany({
        where: { clerkUserId, completedAt: null },
        include: { problem: true },
        orderBy: { priorityScore: "desc" },
        take: 3,
      }),
      prisma.failureAnalysis.findMany({
        where: { clerkUserId },
        orderBy: { createdAt: "desc" },
        take: 100,
      }),
      prisma.microProofAttempt.findMany({
        where: { clerkUserId },
        select: {
          score: true,
          createdAt: true,
          intervalDaysAfterReview: true,
          microProof: { select: { concept: { select: { name: true } } } },
        },
        orderBy: { createdAt: "asc" },
      }),
      prisma.leetCodeSubmission.findMany({
        where: { account: { clerkUserId }, verdict: ACCEPTED_VERDICT },
        select: { problemId: true, timestamp: true, problem: { select: { title: true, difficulty: true } } },
        distinct: ["problemId"],
        orderBy: { timestamp: "desc" },
      }),
    ]);

  // ---- Summary cards ----
  const overallMasteryPercent = masteries.length
    ? Math.round(masteries.reduce((sum, m) => sum + m.masteryScore, 0) / masteries.length)
    : null;
  const conceptsToImprove = masteries.filter((m) => m.status === "WEAK").length;
  const reviewsDueCount = revisionSchedules.filter((s) => s.nextReviewAt <= now).length;
  const problemsSolved = acceptedSubmissions.length;

  // ---- Concept mastery list/chart (weakest first — most actionable) ----
  const masteryList = [...masteries]
    .sort((a, b) => a.masteryScore - b.masteryScore)
    .slice(0, 6)
    .map((m) => ({ concept: m.concept, masteryScore: m.masteryScore, status: m.status }));

  // ---- Mastery trend (real history only, see buildMasteryTrend) ----
  const trend = buildMasteryTrend(microProofAttempts);

  // ---- Revision ----
  const due = revisionSchedules.filter((s) => s.nextReviewAt <= now);
  const upcoming = revisionSchedules.filter((s) => s.nextReviewAt > now);
  const revisionItems = [...due, ...upcoming].slice(0, 3).map((s) => ({
    concept: s.concept,
    isOverdueOrDueToday: s.nextReviewAt <= now,
    label: describeDueLabel(s.nextReviewAt, now),
    status: s.mastery?.status || null,
  }));

  // ---- Recommendations (read-only; masteryScore/priorityLabel joined from
  // data already fetched above, never re-derived by re-running Phase 8) ----
  const masteryByConcept = new Map(masteries.map((m) => [m.concept, m.masteryScore]));
  const recommendationList = recommendations.map((r) => ({
    id: r.id,
    targetConcept: r.targetConcept,
    reason: r.reason,
    priorityScore: r.priorityScore,
    priorityLabel: priorityLabelFor(r.priorityScore),
    masteryScore: masteryByConcept.get(r.targetConcept) ?? null,
    problem: {
      title: r.problem.title,
      difficulty: r.problem.difficulty,
      topicTags: r.problem.topicTags,
      url: r.problem.url,
    },
  }));

  // ---- Failure insights ----
  const failurePatterns = computeFailurePatterns(failureAnalyses);

  // ---- Recent activity ----
  const recentActivity = buildRecentActivity({
    acceptedSubmissions,
    failureAnalyses: failureAnalyses.slice(0, 20),
    microProofAttempts: microProofAttempts.slice(-20),
    masteries,
  });

  return {
    summary: { overallMasteryPercent, conceptsToImprove, reviewsDueCount, problemsSolved },
    masteryList,
    trend,
    revision: { dueCount: reviewsDueCount, items: revisionItems },
    recommendations: recommendationList,
    failurePatterns,
    recentActivity,
  };
}
