// lib/dashboard.js
//
// Phase 10: read-only aggregation for the final dashboard. Every number here
// is derived directly from existing Phase 3-8 tables — no new learning logic,
// no AI calls, nothing fabricated. Recommendations are read from the
// Recommendation table as last generated by Phase 8 (lib/recommendations.js)
// rather than re-running that engine on every dashboard load, so opening the
// dashboard never triggers a fresh Groq call.

import prisma from "@/lib/prisma";
import { normalizeConceptName } from "@/lib/conceptNormalization";
import { ACCEPTED_VERDICT } from "@/lib/constants";
import { priorityLabelFor } from "@/lib/recommendations";

const DAY_MS = 24 * 60 * 60 * 1000;
const MIN_TREND_ATTEMPTS = 3;
const RECENT_ACTIVITY_LIMIT = 8;

function daysBetween(a, b) {
  return (a.getTime() - b.getTime()) / DAY_MS;
}

const WEEKDAY_LABELS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

function dayKey(date) {
  const d = new Date(date);
  return `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;
}

function addDays(date, n) {
  const copy = new Date(date);
  copy.setDate(copy.getDate() + n);
  return copy;
}

/**
 * Consecutive-day activity streak, walking backward from today. A day
 * counts as "active" if it has an accepted submission or a Micro-Proof
 * attempt. Today not yet having activity doesn't break a streak that's
 * still active as of yesterday (the user may just not have opened the app
 * yet today).
 */
function computeStreak({ acceptedSubmissions, microProofAttempts }, now) {
  const activeDays = new Set();
  for (const s of acceptedSubmissions) activeDays.add(dayKey(s.timestamp));
  for (const a of microProofAttempts) activeDays.add(dayKey(a.createdAt));

  let cursor = now;
  if (!activeDays.has(dayKey(cursor))) cursor = addDays(cursor, -1);

  let streak = 0;
  while (activeDays.has(dayKey(cursor))) {
    streak += 1;
    cursor = addDays(cursor, -1);
  }
  return streak;
}

/**
 * Last 7 calendar days (oldest first) of real submission activity —
 * attempted (any verdict) vs. solved (accepted) counts per day. Used by the
 * dashboard's "Learning Activity" chart.
 */
function buildWeeklyActivity(recentSubmissions, now) {
  const days = Array.from({ length: 7 }, (_, i) => addDays(now, i - 6));
  const buckets = new Map(days.map((d) => [dayKey(d), { attempted: 0, solved: 0 }]));

  for (const s of recentSubmissions) {
    const key = dayKey(s.timestamp);
    const bucket = buckets.get(key);
    if (!bucket) continue; // outside the 7-day window
    bucket.attempted += 1;
    if (s.verdict === ACCEPTED_VERDICT) bucket.solved += 1;
  }

  return days.map((d) => {
    const bucket = buckets.get(dayKey(d));
    return {
      day: WEEKDAY_LABELS[d.getDay()],
      date: d.toISOString(),
      attempted: bucket.attempted,
      solved: bucket.solved,
    };
  });
}

function describeDueLabel(nextReviewAt, now) {
  const diffDays = Math.round(daysBetween(nextReviewAt, now));
  if (diffDays <= 0) {
    const overdueDays = Math.abs(diffDays);
    return overdueDays === 0 ? "Due today" : `Overdue by ${overdueDays} day${overdueDays === 1 ? "" : "s"}`;
  }
  if (diffDays === 1) return "Due tomorrow";
  return `Due in ${diffDays} days`;
}

/**
 * Picks the concept with the most Micro-Proof attempts (>= MIN_TREND_ATTEMPTS)
 * and returns its real score history in attempt order. This is genuine
 * stored history (Phase 5 MicroProofAttempt rows) — never fabricated points.
 * Returns null if no concept has enough attempts yet.
 */
function buildMasteryTrend(attempts) {
  const byConcept = new Map();
  for (const a of attempts) {
    const name = normalizeConceptName(a.microProof?.concept?.name);
    if (!name) continue;
    if (!byConcept.has(name)) byConcept.set(name, []);
    byConcept.get(name).push(a);
  }

  let best = null;
  for (const [concept, list] of byConcept) {
    if (list.length < MIN_TREND_ATTEMPTS) continue;
    if (!best || list.length > best.list.length) best = { concept, list };
  }
  if (!best) return null;

  return {
    concept: best.concept,
    data: best.list.map((a, i) => ({
      attempt: i + 1,
      score: a.score,
      date: a.createdAt,
    })),
  };
}

/**
 * Real, per-concept directional trend for the dashboard's Concept Mastery
 * rows — derived from the last two real MicroProofAttempt scores for that
 * concept (score is 0-10; scaled ×10 to read alongside a 0-100 mastery
 * percent). Never a fabricated mastery-history delta: ConceptMastery itself
 * stores no history, so this is the closest real signal available without a
 * schema change. Concepts with fewer than two attempts get no trend
 * ("where possible" — see AGENTS.md dashboard refinement #5).
 */
function buildConceptTrends(microProofAttempts) {
  const byConcept = new Map();
  for (const a of microProofAttempts) {
    const name = normalizeConceptName(a.microProof?.concept?.name);
    if (!name) continue;
    if (!byConcept.has(name)) byConcept.set(name, []);
    byConcept.get(name).push(a);
  }

  const trends = new Map();
  for (const [concept, attempts] of byConcept) {
    if (attempts.length < 2) continue;
    const [prev, last] = attempts.slice(-2);
    const deltaPoints = (last.score - prev.score) * 10;
    if (deltaPoints === 0) continue;
    trends.set(concept, { direction: deltaPoints > 0 ? "up" : "down", deltaPoints: Math.abs(deltaPoints) });
  }
  return trends;
}

function computeFailurePatterns(failureAnalyses) {
  const counts = new Map();
  for (const f of failureAnalyses) {
    const concept = normalizeConceptName(f.concept) || f.concept;
    counts.set(concept, (counts.get(concept) || 0) + 1);
  }
  return Array.from(counts.entries())
    .map(([concept, count]) => ({ concept, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 3);
}

function buildRecentActivity({ acceptedSubmissions, failureAnalyses, microProofAttempts, masteries, limit = RECENT_ACTIVITY_LIMIT }) {
  const events = [];

  for (const s of acceptedSubmissions) {
    events.push({
      type: "SOLVED",
      label: `Solved "${s.problem.title}"`,
      detail: s.problem.difficulty,
      date: s.timestamp,
    });
  }

  for (const f of failureAnalyses) {
    events.push({
      type: "FAILURE",
      label: `Failure analyzed: ${f.concept}`,
      detail: f.failureCategory,
      date: f.createdAt,
    });
  }

  for (const a of microProofAttempts) {
    const conceptName = a.microProof?.concept?.name || "a concept";
    const isRevision = a.intervalDaysAfterReview !== null && a.intervalDaysAfterReview !== undefined;
    events.push({
      type: isRevision ? "REVISION" : "MICROPROOF",
      label: isRevision ? `Revision reviewed: ${conceptName}` : `Micro-Proof completed: ${conceptName}`,
      detail: `Score ${a.score}/10`,
      date: a.createdAt,
    });
  }

  for (const m of masteries) {
    if (m.updatedAt.getTime() === m.createdAt.getTime()) continue; // never re-evaluated since creation
    events.push({
      type: "MASTERY",
      label: `Mastery updated: ${m.concept}`,
      detail: `${m.masteryScore}%`,
      date: m.updatedAt,
      status: m.status, // WEAK/DEVELOPING/STRONG — lets the UI label this signal precisely
    });
  }

  return events.sort((a, b) => b.date - a.date).slice(0, limit);
}

/**
 * Full learning-signal history for the "View all" link off the dashboard's
 * Recent Learning Signals section (see app/activity/page.js). Same real
 * event-building logic as the dashboard summary, just with a much larger
 * limit and its own (larger) queries — kept separate from
 * getDashboardData so the dashboard's own query shape/perf is untouched.
 *
 * @param {string} clerkUserId
 * @param {{limit?: number}} [options]
 */
export async function getActivityHistory(clerkUserId, { limit = 50 } = {}) {
  const [masteries, failureAnalyses, microProofAttempts, acceptedSubmissions] = await Promise.all([
    prisma.conceptMastery.findMany({ where: { clerkUserId } }),
    prisma.failureAnalysis.findMany({
      where: { clerkUserId },
      orderBy: { createdAt: "desc" },
      take: limit,
    }),
    prisma.microProofAttempt.findMany({
      where: { clerkUserId },
      select: {
        score: true,
        createdAt: true,
        intervalDaysAfterReview: true,
        microProof: { select: { concept: { select: { name: true } } } },
      },
      orderBy: { createdAt: "desc" },
      take: limit,
    }),
    prisma.leetCodeSubmission.findMany({
      where: { account: { clerkUserId }, verdict: ACCEPTED_VERDICT },
      select: { problemId: true, timestamp: true, problem: { select: { title: true, difficulty: true } } },
      distinct: ["problemId"],
      orderBy: { timestamp: "desc" },
      take: limit,
    }),
  ]);

  return buildRecentActivity({ acceptedSubmissions, failureAnalyses, microProofAttempts, masteries, limit });
}

/**
 * Fetches and aggregates everything the dashboard needs in one pass.
 * Every query is scoped to `clerkUserId`. Server-only.
 *
 * @param {string} clerkUserId
 * @returns {Promise<object>}
 */
export async function getDashboardData(clerkUserId) {
  const now = new Date();

  const sevenDaysAgo = addDays(now, -6);
  sevenDaysAgo.setHours(0, 0, 0, 0);

  const [
    masteries,
    revisionSchedules,
    recommendations,
    failureAnalyses,
    microProofAttempts,
    acceptedSubmissions,
    recentSubmissions,
  ] = await Promise.all([
      prisma.conceptMastery.findMany({ where: { clerkUserId } }),
      prisma.revisionSchedule.findMany({
        where: { clerkUserId },
        include: { mastery: { select: { status: true } } },
        orderBy: { nextReviewAt: "asc" },
      }),
      prisma.recommendation.findMany({
        where: { clerkUserId, completedAt: null },
        include: { problem: true },
        orderBy: { priorityScore: "desc" },
        take: 3,
      }),
      prisma.failureAnalysis.findMany({
        where: { clerkUserId },
        orderBy: { createdAt: "desc" },
        take: 100,
      }),
      prisma.microProofAttempt.findMany({
        where: { clerkUserId },
        select: {
          score: true,
          createdAt: true,
          intervalDaysAfterReview: true,
          microProof: { select: { concept: { select: { name: true } } } },
        },
        orderBy: { createdAt: "asc" },
      }),
      prisma.leetCodeSubmission.findMany({
        where: { account: { clerkUserId }, verdict: ACCEPTED_VERDICT },
        select: { problemId: true, timestamp: true, problem: { select: { title: true, difficulty: true } } },
        distinct: ["problemId"],
        orderBy: { timestamp: "desc" },
      }),
      prisma.leetCodeSubmission.findMany({
        where: { account: { clerkUserId }, timestamp: { gte: sevenDaysAgo } },
        select: { timestamp: true, verdict: true },
      }),
    ]);

  // ---- Summary cards ----
  const overallMasteryPercent = masteries.length
    ? Math.round(masteries.reduce((sum, m) => sum + m.masteryScore, 0) / masteries.length)
    : null;
  const conceptsToImprove = masteries.filter((m) => m.status === "WEAK").length;
  const reviewsDueCount = revisionSchedules.filter((s) => s.nextReviewAt <= now).length;
  const problemsSolved = acceptedSubmissions.length;

  // ---- Concept mastery list/chart (weakest first — most actionable) ----
  const conceptTrends = buildConceptTrends(microProofAttempts);
  const masteryList = [...masteries]
    .sort((a, b) => a.masteryScore - b.masteryScore)
    .slice(0, 6)
    .map((m) => ({
      concept: m.concept,
      masteryScore: m.masteryScore,
      status: m.status,
      trend: conceptTrends.get(m.concept) || null,
    }));

  // ---- Mastery trend (real history only, see buildMasteryTrend) ----
  const trend = buildMasteryTrend(microProofAttempts);

  // ---- Revision ----
  const due = revisionSchedules.filter((s) => s.nextReviewAt <= now);
  const upcoming = revisionSchedules.filter((s) => s.nextReviewAt > now);
  const revisionItems = [...due, ...upcoming].slice(0, 3).map((s) => ({
    concept: s.concept,
    isOverdueOrDueToday: s.nextReviewAt <= now,
    label: describeDueLabel(s.nextReviewAt, now),
    status: s.mastery?.status || null,
  }));

  // ---- Recommendations (read-only; masteryScore/priorityLabel joined from
  // data already fetched above, never re-derived by re-running Phase 8) ----
  const masteryByConcept = new Map(masteries.map((m) => [m.concept, m.masteryScore]));
  const recommendationList = recommendations.map((r) => ({
    id: r.id,
    targetConcept: r.targetConcept,
    reason: r.reason,
    priorityScore: r.priorityScore,
    priorityLabel: priorityLabelFor(r.priorityScore),
    masteryScore: masteryByConcept.get(r.targetConcept) ?? null,
    problem: {
      title: r.problem.title,
      difficulty: r.problem.difficulty,
      topicTags: r.problem.topicTags,
      url: r.problem.url,
    },
  }));

  // ---- Failure insights ----
  const failurePatterns = computeFailurePatterns(failureAnalyses);

  // ---- Recent activity ----
  const recentActivity = buildRecentActivity({
    acceptedSubmissions,
    failureAnalyses: failureAnalyses.slice(0, 20),
    microProofAttempts: microProofAttempts.slice(-20),
    masteries,
  });

  // ---- Streak + weekly activity chart (real submission/attempt timestamps) ----
  const streakDays = computeStreak({ acceptedSubmissions, microProofAttempts }, now);
  const weeklyActivity = buildWeeklyActivity(recentSubmissions, now);

  return {
    summary: { overallMasteryPercent, conceptsToImprove, reviewsDueCount, problemsSolved, streakDays },
    masteryList,
    trend,
    revision: { dueCount: reviewsDueCount, items: revisionItems },
    recommendations: recommendationList,
    failurePatterns,
    recentActivity,
    weeklyActivity,
  };
}
