// lib/problemsInsights.js
//
// Read-only presentation-layer aggregation for the Problems page. Mastery
// scores are read as-is from ConceptMastery (lib/mastery.js's own math,
// never recomputed here); the "Recommended" filter reads the already-
// persisted Recommendation table (generated by /recommendations via
// lib/recommendations.js) rather than re-running that engine — visiting
// /problems never triggers a fresh Groq call or a new recommendation batch.
// Mirrors the read-only aggregation pattern used throughout the rest of the
// app (lib/dashboard.js, lib/masteryInsights.js, lib/revisionInsights.js,
// lib/recommendationsInsights.js).

import prisma from "@/lib/prisma";
import { normalizeConceptName } from "@/lib/conceptNormalization";
import { ACCEPTED_VERDICT, FAILING_VERDICTS } from "@/lib/constants";
import { buildConceptTrends } from "@/lib/dashboard";

// Bounded fetch — this app's global catalog tops out in the low thousands
// (see lib/leetcodeCatalog.js), and per-user filters (status/topic) need to
// run in JS after joining real per-user data, so a generous but capped
// candidate set (rather than fetching + joining the entire catalog on every
// request) keeps this a "focused" implementation rather than a fully
// generalized search index.
const FETCH_CAP = 300;
export const PAGE_SIZE = 20;

export const DIFFICULTIES = ["Easy", "Medium", "Hard"];

// A curated filter vocabulary (not a claim that these are the only topics
// in the catalog) — the same kind of fixed, small option list the existing
// difficulty filter already uses.
export const TOPICS = [
  "Array",
  "String",
  "Hash Table",
  "Binary Search",
  "Linked List",
  "Tree",
  "Graph",
  "Dynamic Programming",
  "Greedy",
  "Two Pointers",
  "Sliding Window",
  "Stack",
  "Heap",
  "Backtracking",
];

export const STATUS_FILTERS = ["recommended", "weak", "solved"];

function daysAgo(date, now) {
  return Math.max(0, Math.round((now.getTime() - date.getTime()) / (24 * 60 * 60 * 1000)));
}

function describeLastAttempted(days) {
  if (days === 0) return "Today";
  if (days === 1) return "Yesterday";
  return `${days} days ago`;
}

// Best-effort problem -> concept match, same approach already used
// elsewhere (topic tag -> normalized concept name).
function matchConcept(topicTags, masteryByConcept) {
  for (const tag of topicTags) {
    const concept = normalizeConceptName(tag);
    if (concept && masteryByConcept.has(concept)) return concept;
  }
  return null;
}

function computeStatus({ mastery, trend }) {
  if (!mastery) return "NOT_ATTEMPTED";
  if (mastery.status === "STRONG") return "MASTERED";
  if (mastery.status === "DEVELOPING") return "IMPROVING";
  return trend?.direction === "up" ? "ATTENTION" : "WEAK";
}

// A short, honest "why practice this" line. Prefers the real, Groq-authored
// Recommendation.reason when this exact problem is actively recommended;
// otherwise falls back to a real signal (the concept's most recent
// FailureAnalysis root cause, or its trend), never invented copy with no
// real basis. Returns null when there's genuinely nothing to say yet.
function buildInsight({ recommendedReason, matchedConcept, mostRecentRootCause, status }) {
  if (recommendedReason) return recommendedReason;
  if (!matchedConcept) return null;
  if (mostRecentRootCause) return `Targets a recent mistake: ${mostRecentRootCause}`;
  if (status === "ATTENTION") return `${matchedConcept} is improving — this keeps that momentum going.`;
  if (status === "WEAK") return `Reinforces ${matchedConcept}, currently one of your weaker concepts.`;
  if (status === "MASTERED") return `You've got a strong handle on ${matchedConcept} — good for staying sharp.`;
  return null;
}

/**
 * @param {string} clerkUserId
 * @param {{q?:string, difficulty?:string, topic?:string, status?:string, page?:number}} params
 */
export async function getProblemsListData(clerkUserId, params) {
  const { q = "", difficulty = null, topic = null, status: statusFilter = null, page = 1 } = params;

  const [catalogRows, allSubmissions, masteries, microProofAttempts, failureAnalyses, activeRecommendations] =
    await Promise.all([
      prisma.leetCodeProblemCatalog.findMany({
        where: {
          ...(q ? { title: { contains: q, mode: "insensitive" } } : {}),
          ...(difficulty ? { difficulty } : {}),
          ...(topic ? { topicTags: { has: topic } } : {}),
        },
        orderBy: { title: "asc" },
        take: FETCH_CAP,
      }),
      prisma.leetCodeSubmission.findMany({
        where: { account: { clerkUserId } },
        select: { verdict: true, timestamp: true, id: true, problem: { select: { titleSlug: true } } },
        orderBy: { timestamp: "desc" },
      }),
      prisma.conceptMastery.findMany({ where: { clerkUserId } }),
      prisma.microProofAttempt.findMany({
        where: { clerkUserId },
        select: { score: true, createdAt: true, microProof: { select: { concept: { select: { name: true } } } } },
        orderBy: { createdAt: "asc" },
      }),
      prisma.failureAnalysis.findMany({
        where: { clerkUserId },
        orderBy: { createdAt: "desc" },
        select: { concept: true, rootCause: true },
      }),
      prisma.recommendation.findMany({
        where: { clerkUserId, completedAt: null },
        include: { problem: { select: { titleSlug: true } } },
      }),
    ]);

  const now = new Date();
  const masteryByConcept = new Map(masteries.map((m) => [m.concept, m]));
  const trends = buildConceptTrends(microProofAttempts);
  const recommendationBySlug = new Map(activeRecommendations.map((r) => [r.problem.titleSlug, r]));

  // Group this user's submissions by problem slug — one pass covers every
  // catalog row below instead of one query per row.
  const submissionsBySlug = new Map();
  for (const s of allSubmissions) {
    const slug = s.problem.titleSlug;
    if (!submissionsBySlug.has(slug)) submissionsBySlug.set(slug, []);
    submissionsBySlug.get(slug).push(s);
  }

  const enriched = catalogRows.map((p) => {
    const submissions = submissionsBySlug.get(p.slug) || [];
    const hasAccepted = submissions.some((s) => s.verdict === ACCEPTED_VERDICT);
    const latestFailed = submissions.find((s) => FAILING_VERDICTS.includes(s.verdict));
    const latestAny = submissions[0] || null;

    const matchedConcept = matchConcept(p.topicTags, masteryByConcept);
    const mastery = matchedConcept ? masteryByConcept.get(matchedConcept) : null;
    const trend = matchedConcept ? trends.get(matchedConcept) || null : null;
    const recommendation = recommendationBySlug.get(p.slug) || null;
    const mostRecentFailure = matchedConcept
      ? failureAnalyses.find((f) => (normalizeConceptName(f.concept) || f.concept) === matchedConcept)
      : null;

    const status = computeStatus({ mastery, trend });

    return {
      id: p.id,
      title: p.title,
      difficulty: p.difficulty,
      topicTags: p.topicTags,
      url: p.url,
      concept: matchedConcept,
      masteryScore: mastery?.masteryScore ?? null,
      trend,
      status,
      isSolved: hasAccepted,
      isRecommended: Boolean(recommendation),
      attempts: submissions.length,
      lastAttempted: latestAny ? describeLastAttempted(daysAgo(latestAny.timestamp, now)) : null,
      lastAttemptedRaw: latestAny?.timestamp.toISOString() || null,
      latestFailedSubmissionId: latestFailed?.id || null,
      latestAcceptedSubmissionId: hasAccepted ? submissions.find((s) => s.verdict === ACCEPTED_VERDICT)?.id : null,
      learningSignal: mostRecentFailure?.rootCause || null,
      insight: buildInsight({
        recommendedReason: recommendation?.reason || null,
        matchedConcept,
        mostRecentRootCause: mostRecentFailure?.rootCause || null,
        status,
      }),
    };
  });

  const filtered = enriched.filter((p) => {
    if (statusFilter === "recommended") return p.isRecommended;
    if (statusFilter === "weak") return p.status === "WEAK" || p.status === "ATTENTION";
    if (statusFilter === "solved") return p.isSolved;
    return true;
  });

  const totalCount = filtered.length;
  const start = (page - 1) * PAGE_SIZE;
  const pageItems = filtered.slice(start, start + PAGE_SIZE);

  return {
    problems: pageItems,
    totalCount,
    totalPages: Math.max(1, Math.ceil(totalCount / PAGE_SIZE)),
    hasActiveRecommendations: activeRecommendations.length > 0,
  };
}
